default_platform :ios

platform :ios do

  before_all do
      ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Enigma", output_directory: ".fastlane/ios_test_output")
    xcov(scheme: "Enigma", output_directory: ".fastlane/ios_xcov_report")

    scan(scheme: "EnigmaMac", output_directory: ".fastlane/mac_test_output")
    xcov(scheme: "EnigmaMac", output_directory: ".fastlane/mac_xcov_report")
  end
end
